<?

/* Display help and module information
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function lodspeakr_help($path, $arg) {
  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help#lodspeakr":
      $output = '<p>'.  t("Displays links to nodes created on this date") .'</p>';
      break;
  }
  return $output;
} // function lodspeakr_help

function lodspeakr_perm() {
  return array('access lodspeakr content', 'administer lodspeakr');
} // function lodspeakr_perm()

function lodspeakr_admin() {
  $form = array();

  $form['lodspeakr_endpoint'] = array(
    '#type' => 'textfield',
    '#title' => t('SPARQL Endpoint'),
    '#default_value' => variable_get('lodspeakr_sparql_endpoint', 'http://localhost/sparql'),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The maximum umber of links to display in the block."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}


function lodspeakr_menu() {

  $items = array();

  $items['admin/settings/lodspeakr'] = array(
    'title' => t('On this date module settings'),
    'description' => t('Description of your On this date settings page'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lodspeakr_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );

  
  $items['lodspeakr'] = array(
    'title' => 'LODSPeaKr',
    'access arguments' => array('access lodspeakr content'),
    'page callback' => 'lodspeakr_all',
    'type' => MENU_CALLBACK
  );
  return $items;
}


function lodspeakr_all(){
  global $base_url;
  $page_content = '';
  $keys = $_REQUEST['destination'] ? $_REQUEST['destination'] : $_REQUEST['q'];
  $keys = $_GET['ls'];
  $uri = $base_url."/".$keys;
  if(!require_once('lib/lodspeakr/index.inc')){
    drupal_set_message("Couldn't load LODSPeaKr", 'error', TRUE);
    return $page_content;
  }
  $aux = _lodspeakr_main($uri);
  $page_content .= $aux;
  return $page_content;
}

